package com.company.enums;

public enum UserDetailEnum {

    ORGANIZATION, POSITION, INTERNSHIP, SALARY, PASSPORT_PHOTO_SCANNER , PASSPORT_PHOTO_ADDRESS, PASSPORT_AND_YOU, PHONE_NUMBER,
    ADD_NUMBER, CARD, VALIDITY_PERIOD, CARD_PHONE_NUMBER
}
